### ISSUE TITLE
Class 'Trax\Core\TraxCoreServiceProvider' not found - during composer install

### ISSUE THREAD

**Issue by cbake6807** [trax-project/trax2-starter-lrs#1]
Receiving the following error on `composer install` and some `artisan` commands. 

root@ip-172-31-201-109:/srv/traxlrs2# composer -V
Composer 1.10.1 2020-03-13 20:34:27

root@ip-172-31-201-109:/srv/traxlrs2# nginx -v
nginx version: nginx/1.18.0 (Ubuntu)

root@ip-172-31-201-109:/srv/traxlrs2# php artisan key:generate

In ProviderRepository.php line 208:

  Class 'Trax\Core\TraxCoreServiceProvider' not found

root@ip-172-31-201-109:/srv/traxlrs2# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

`Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 99 installs, 0 updates, 0 removals
  - Installing doctrine/inflector (2.0.3): Downloading (100%)
  - Installing doctrine/lexer (1.2.1): Loading from cache
  - Installing dragonmantank/cron-expression (v2.3.1): Loading from cache
  - Installing voku/portable-ascii (1.5.6): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.22.0): Loading from cache
  - Installing phpoption/phpoption (1.7.5): Downloading (100%)
  - Installing vlucas/phpdotenv (v4.2.0): Downloading (100%)
  - Installing symfony/css-selector (v5.2.3): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.3): Loading from cache
  - Installing symfony/polyfill-php80 (v1.22.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.22.0): Loading from cache
  - Installing symfony/var-dumper (v5.2.3): Downloading (100%)
  - Installing symfony/deprecation-contracts (v2.2.0): Loading from cache
  - Installing symfony/routing (v5.2.3): Downloading (100%)
  - Installing symfony/process (v5.2.3): Downloading (100%)
  - Installing symfony/polyfill-php73 (v1.22.0): Loading from cache
  - Installing symfony/polyfill-php72 (v1.22.0): Loading from cache
  - Installing symfony/polyfill-intl-normalizer (v1.22.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.22.0): Loading from cache
  - Installing symfony/mime (v5.2.3): Loading from cache
  - Installing symfony/http-foundation (v5.2.3): Downloading (100%)
  - Installing symfony/http-client-contracts (v2.3.1): Loading from cache
  - Installing psr/event-dispatcher (1.0.0): Downloading (100%)
  - Installing symfony/event-dispatcher-contracts (v2.2.0): Downloading (100%)
  - Installing symfony/event-dispatcher (v5.2.3): Downloading (100%)
  - Installing psr/log (1.1.3): Loading from cache
  - Installing symfony/error-handler (v5.2.3): Downloading (100%)
  - Installing symfony/http-kernel (v5.2.3): Downloading (100%)
  - Installing symfony/finder (v5.2.3): Downloading (100%)
  - Installing symfony/polyfill-intl-grapheme (v1.22.0): Downloading (100%)
  - Installing symfony/string (v5.2.3): Downloading (100%)
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/service-contracts (v2.2.0): Loading from cache
  - Installing symfony/console (v5.2.3): Downloading (100%)
  - Installing symfony/polyfill-iconv (v1.22.0): Loading from cache
  - Installing egulias/email-validator (2.1.25): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.5): Loading from cache
  - Installing ramsey/collection (1.1.3): Downloading (100%)
  - Installing brick/math (0.9.2): Downloading (100%)
  - Installing ramsey/uuid (4.1.1): Downloading (100%)
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing opis/closure (3.6.1): Loading from cache
  - Installing symfony/translation-contracts (v2.3.0): Loading from cache
  - Installing symfony/translation (v5.2.3): Downloading (100%)
  - Installing nesbot/carbon (2.44.0): Downloading (100%)
  - Installing monolog/monolog (2.2.0): Downloading (100%)
  - Installing league/mime-type-detection (1.7.0): Loading from cache
  - Installing league/flysystem (1.1.3): Loading from cache
  - Installing league/commonmark (1.5.7): Downloading (100%)
  - Installing laravel/framework (v7.30.4): Downloading (100%)
  - Installing fideloper/proxy (4.4.1): Loading from cache
  - Installing asm89/stack-cors (1.3.0): Downloading (100%)
  - Installing fruitcake/laravel-cors (v1.0.6): Downloading (100%)
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.7.0): Loading from cache
  - Installing guzzlehttp/promises (1.4.0): Loading from cache
  - Installing guzzlehttp/guzzle (6.5.5): Loading from cache
  - Installing nikic/php-parser (v4.10.4): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (v0.1.1): Loading from cache
  - Installing psy/psysh (v0.10.6): Downloading (100%)
  - Installing laravel/tinker (v2.6.0): Downloading (100%)
  - Installing laravel/ui (v2.0.0): Downloading (100%)
  - Installing filp/whoops (2.9.2): Loading from cache
  - Installing facade/ignition-contracts (1.0.2): Downloading (100%)
  - Installing facade/flare-client-php (1.3.7): Downloading (100%)
  - Installing facade/ignition (2.5.10): Downloading (100%)
  - Installing fzaninotto/faker (v1.9.2): Loading from cache
  - Installing hamcrest/hamcrest-php (v2.0.1): Loading from cache
  - Installing mockery/mockery (1.4.2): Downloading (100%)
  - Installing nunomaduro/collision (v4.3.0): Downloading (100%)
  - Installing webmozart/assert (1.9.1): Loading from cache
  - Installing phpdocumentor/reflection-common (2.2.0): Loading from cache
  - Installing phpdocumentor/type-resolver (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (5.2.2): Loading from cache
  - Installing phpunit/php-token-stream (4.0.4): Downloading (100%)
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/type (1.1.4): Downloading (100%)
  - Installing sebastian/resource-operations (2.0.2): Loading from cache
  - Installing sebastian/recursion-context (3.0.1): Loading from cache
  - Installing sebastian/object-reflector (1.1.2): Loading from cache
  - Installing sebastian/object-enumerator (3.0.4): Loading from cache
  - Installing sebastian/global-state (3.0.1): Downloading (100%)
  - Installing sebastian/exporter (3.1.3): Loading from cache
  - Installing sebastian/environment (4.2.4): Loading from cache
  - Installing sebastian/diff (3.0.3): Loading from cache
  - Installing sebastian/comparator (3.0.3): Loading from cache
  - Installing phpunit/php-timer (2.1.3): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (2.0.3): Loading from cache
  - Installing theseer/tokenizer (1.2.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (7.0.14): Downloading (100%)
  - Installing doctrine/instantiator (1.4.0): Loading from cache
  - Installing phpspec/prophecy (1.12.2): Loading from cache
  - Installing phar-io/version (3.0.4): Downloading (100%)
  - Installing phar-io/manifest (2.0.1): Downloading (100%)
  - Installing myclabs/deep-copy (1.10.2): Loading from cache
  - Installing phpunit/phpunit (8.5.14): Downloading (100%)
voku/portable-ascii suggests installing ext-intl (Use Intl for transliterator_transliterate() support)
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/polyfill-intl-normalizer suggests installing ext-intl (For best performance)
symfony/polyfill-intl-idn suggests installing ext-intl (For best performance)
symfony/http-client-contracts suggests installing symfony/http-client-implementation
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
symfony/polyfill-intl-grapheme suggests installing ext-intl (For best performance)
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/lock
egulias/email-validator suggests installing ext-intl (PHP Internationalization Libraries are required to use the SpoofChecking validation)
swiftmailer/swiftmailer suggests installing ext-intl (Needed to support internationalized email addresses)
ramsey/uuid suggests installing ext-bcmath (Enables faster math with arbitrary-precision integers using BCMath.)
ramsey/uuid suggests installing ext-gmp (Enables faster math with arbitrary-precision integers using GMP.)
ramsey/uuid suggests installing ext-uuid (Enables the use of PeclUuidTimeGenerator and PeclUuidRandomGenerator.)
ramsey/uuid suggests installing paragonie/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing elasticsearch/elasticsearch (Allow sending log messages to an Elasticsearch server via official client)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongodb (Allow sending log messages to a MongoDB server (via driver))
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server (via library))
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver, DynamoDb failed job storage and SES mail driver (^3.155).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (^2.6).)
laravel/framework suggests installing ext-gd (Required to use Illuminate\Http\Testing\FileFactory::image().)
laravel/framework suggests installing ext-memcached (Required to use the memcache cache driver.)
laravel/framework suggests installing ext-redis (Required to use the Redis cache and queue drivers (^4.0|^5.0).)
laravel/framework suggests installing fakerphp/faker (Required to use the eloquent factory builder (^1.9.1).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
laravel/framework suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
laravel/framework suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
laravel/framework suggests installing nyholm/psr7 (Required to use PSR-7 bridging features (^1.2).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (^4.0).)
laravel/framework suggests installing predis/predis (Required to use the predis connector (^1.1.2).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (^4.0).)
laravel/framework suggests installing symfony/cache (Required to PSR-6 cache bridge (^5.0).)
laravel/framework suggests installing symfony/filesystem (Required to create relative storage directory symbolic links (^5.0).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to use PSR-7 bridging features (^2.0).)
laravel/framework suggests installing wildbit/swiftmailer-postmark (Required to use Postmark mail driver (^3.0).)
guzzlehttp/psr7 suggests installing laminas/laminas-httphandlerrunner (Emit PSR-7 responses)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
facade/ignition suggests installing laravel/telescope (^3.1)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.7.2)
phpunit/phpunit suggests installing ext-soap (*)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0.0)
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Deprecation Notice: Class Trax\Lrs\LrsServiceProvider located in ./services/trax/lrs/src/LrsServiceProvider.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Trax\Lrs\Console\CreateAdminCommand located in ./services/trax/lrs/src/Console/CreateAdminCommand.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Trax\Lrs\Console\AdminCommand located in ./services/trax/lrs/src/Console/AdminCommand.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Trax\Lrs\Console\ListAdminCommand located in ./services/trax/lrs/src/Console/ListAdminCommand.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Trax\Lrs\Console\DeleteAdminCommand located in ./services/trax/lrs/src/Console/DeleteAdminCommand.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Trax\Lrs\Console\UpdateAdminCommand located in ./services/trax/lrs/src/Console/UpdateAdminCommand.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Trax\Lrs\BasicClients\BasicClientController located in ./services/trax/lrs/src/BasicClients/BasicClientController.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Trax\Lrs\BasicClients\BasicClientService located in ./services/trax/lrs/src/BasicClients/BasicClientService.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 208:

  Class 'Trax\Core\TraxCoreServiceProvider' not found

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

root@ip-172-31-201-109:/srv/traxlrs2# chmod -R 777 bootstrap/cache
root@ip-172-31-201-109:/srv/traxlrs2# chmod -R 777 storage`

![ ](https://user-images.githubusercontent.com/833624/106928008-baf11000-66e0-11eb-994b-0955881d58e0.png)

**Comment by sfraysse** [comment]
Composer is looking for `Trax\Core\TraxCoreServiceProvider` which is part of **TRAX Framework**.

TRAX Framework is a **Git submodule** and should have been installed during the Git command: `git clone --recursive --branch beta1 https://github.com/trax-project/trax2-starter-lrs traxlrs`, thanks to the `--recursive` option.

Could you check if it has been installed please? Does the **./services/trax/framework** folder exist?

If for any reason this folder is missing, you can try to reinstall it with: `git submodule update`.
Check again if the **./services/trax/framework** folder exists.

Then, `composer dumpautoload`.

**Comment by cbake6807** [comment]
Thanks Sebastien. I did not realize I cloned it improperly. 

I now have the framework installed and the app appears to be working correctly. Sorry for incorrectly reporting an issue that was just user error :)
