### ISSUE TITLE
Can't receive statements 

### ISSUE THREAD

**Issue by HichemUchiwa** [trax-project/trax2-starter-lrs#11]
Hello
I have almost the same issue than #4 . I followed all steps of the installation and URL: endpoint/about works. However the URL: endpoint/statements doesn't work and like @mstimvol when I copy the service endpoint url of the client and configure my LMS using this url, I receive no statements.
Thank you for considering my request :)

**Comment by sfraysse** [comment]
Hi,

First of all, before testing with your LMS, you should use a simple tool like https://adlnet.github.io/xapi-lab/#tab-smar-receiving to test the LRS access. Add the `/` char at the end of the endpoint and use correct credentials, then try to get statements and see if you get an error.

When it works, go to your LMS and:
- Check that your LMS is well configured, with or without the `/` char at the end of the endpoint, depending of the LMS.
- Check that you entered the right credentials.
- Check there is no security issue between your LMS and LRS

Like #4, it's an LMS configuration issue, not an LRS issue, so I close.
