### ISSUE TITLE
Impossible de se connecter avec le compte admin

### ISSUE THREAD

**Issue by Chrys65** [trax-project/trax2-starter-lrs#12]
Bonjour M. Fraysse,

Nous revoici aux manettes pour tenter de déployer un LMS avec le Trax, après de trop longs mois de suspension....

J'ai installé le trax **conformément  aux préconisations**. mais il m'est impossible de me logguer en admin sur la page de connexion.
(J'ai retrouvé un post clôuré qui traitait du même problème mais sans avoir de piste de résolution.)

login:admin@traxlrs.com / pswd: celui généré => connexion impossible
J'ai modifié le mot de passe en mettant aaaaaa comme indiqué dans le post clos=> cela ne fonctionne toujours pas

J'ai une erreur 404, lorsque  j'active les outils de développement de la page web.

Dans le fichier error.log: "File does not exist /var/www/html/traxlrs/vendor/trax/api/auth/login"

En effet, le répertoire /var/www/html/traxlrs/vendor/trax n'existe pas!

Je vous remercie par avance pour votre aide précieuse.

Cordialement,

Chrystèle (nous avions suivi votre formation en décembre dernier)

**Comment by sfraysse** [comment]
Bonjour Christelle,

En premier lieu, il faudrait vérifier ce point de la procédure d'install https://github.com/trax-project/trax2-starter-lrs#web-server car logiquement, il devrait aller chercher le fichier dans `public` et non `vendor` qui ne devrait pas être accessible.

Vérifiez également que l'URL rewriting est bien activé https://github.com/trax-project/trax2-starter-lrs#apache-24 car il ne s'agit pas d'un fichier mais d'une route, qui devrait être interprétée.

Si cela ne résoud pas votre problème, contactez-moi directement par mail ou tél afin que l'on cale un moment en visio pour essayer de comprendre votre problème.

Sébastien

**Comment by Chrys65** [comment]
Bonjour Sébastien,

En effet, j'avais fait une erreur dans le fichier de configuration du serveur web. Pas au niveau du document root, mais sur un alias qui concernait  vendor (j'avais replaqué une ancienne conf).
Encore merci pour votre réponse rapide et votre aide.

Chrystèle

**Comment by sfraysse** [comment]
Il n'y a pas de quoi. Bon courage pour la suite !
