### ISSUE TITLE
Fix permissions in installation guide

### ISSUE THREAD

**Issue by DonavanMartin** [trax-project/trax2-starter-lrs#14]
Hi,
it could really better if you can fix permissions installing guide by adding secures examples and removing 777 permissions:
chmod -R 777 bootstrap/cache
chmod -R 777 storage

**Comment by sfraysse** [comment]
Hi @AlgoSolu,
Thanks for your feedback. Fixing permissions depends on how you define ownerships on your server, so there is probably not a single approach. However, I tried to improve the installation guide with the 2.0.1 release that has just been published: https://github.com/trax-project/trax2-starter-lrs#file-permissions.
Tell me what you think.

**Comment by donavan-tangible** [comment]
Please see PR for this commit: https://github.com/trax-project/trax2-starter-lrs/commit/7266e775c1e0a39aed780ef071c72d9eeb64507b

**Comment by DonavanMartin** [comment]
Please see PR for this commit: https://github.com/trax-project/trax2-starter-lrs/pull/24/commits/7266e775c1e0a39aed780ef071c72d9eeb64507b
