### ISSUE TITLE
Docker ETA

### ISSUE THREAD

**Issue by TheRealBarenziah** [trax-project/trax2-starter-lrs#15]
Hello !

I've see #8 and [the open PR](https://github.com/trax-project/trax2-starter-lrs/pull/10) but the image mentioned by jeremyVignelles doesn't exist anymore, and there is an issue pulling the [only image I could find](https://hub.docker.com/r/traxlrs/starter):
`Error response from daemon: manifest for traxlrs/starter:latest not found: manifest unknown: manifest unknown`

Am I missing something here? And if not, do you have some ETA regarding this?

Thank you very much :)

**Comment by sfraysse** [comment]
Hi @TheRealBarenziah,
There is currently no official Docker image provided for this project.
This will come at some point but I have no schedule for that.
In the meantime, fell free to explore the question and share your solution.
