### ISSUE TITLE
How to cite ?

### ISSUE THREAD

**Issue by Qwarctick** [trax-project/trax2-starter-lrs#17]
Hello @sfraysse,
Do you have a bib ref citation available for scientific publication ?

Something like:

```bib
@software{traxlrs,
  author = {{S. Fraysse}},
  title = {Trax2-LRS},
  url = {traxlrs.com/},
  version = {2.0.1},
  date = {2022-02-22},
}
```
Thanks

**Comment by sfraysse** [comment]
Hi @PhilippeNoel1,
No, I don't and I am not aware of that.
How can I create such a ref?
