### ISSUE TITLE
Laravel 9 and php 8.1 support

### ISSUE THREAD

**Issue by trippo** [trax-project/trax2-starter-lrs#18]
Is support for laravel 9 and php 8.1 planned?

**Comment by sfraysse** [comment]
Hi @trippo,
Laravel 9 drops the support of PHP 7.x so we don't want to move to Laravel 9 immediately.
But we will move to Laravel 9 with the next major release of TRAX LRS, scheduled for mid 2023.

**Comment by sfraysse** [comment]
TRAX LRS has been upgraded to support Laravel 10 with PHP 8.1 to 8.3
