### ISSUE TITLE
New install - getting a URL requested not found

### ISSUE THREAD

**Issue by rmeske** [trax-project/trax2-starter-lrs#19]
Hello,

I installed 2.01 Starter Edition following the instructions but when visiting the site, it is trying to open /lrs and giving a 404 error.  

I verified I set the APP_URL correctly in .env and am using the same URL to access the site.  I have rerun php artisan config:cache to ensure the config was loaded properly.

I am running:
Ubuntu 20.04.4
Apache 2.4.41 
PHP 7.4.3 
SSL is enabled

I am able create a basic html and php file in the public folder and access them successfully.

Besides setting the document root to the public folder are there specific directory settings for the folder that should be set?

**Comment by sfraysse** [comment]
Hi @rmeske,

Your installation has a `/public/.htaccess` file with some directives that must be applied by Apache.

In the `httpd.conf` file of Apache, you should try to set the `AllowOverride` option to `All`. Something like:
```
<Directory "path/to/laravel/project/public">
    Allowoverride All
</Directory>
```
Please, tell me if this solves the issue.

**Comment by rmeske** [comment]
Hi @sfraysse, 

Thank you, that fixed the issue.  Should have looked closer at the files in that folder.

Seems like it should be included in the README installation instructions.

**Comment by sfraysse** [comment]
You are right, I will include this information in the README...

**Comment by arladmin** [comment]
Hi @sfraysse , is there another workaround for this, because i'm using a Shared Hosting platform which does not allow making changes to httpd.conf ?

**Comment by sfraysse** [comment]
Hi @arladmin,
No, I don't have any workaround for this. You should have the control on your server.
