### ISSUE TITLE
CSRF token mismatch during login on Firefox

### ISSUE THREAD

**Issue by kieranmathieson** [trax-project/trax2-starter-lrs#2]
Login fails on Firefox. Chrome OK. Already did the git pull origin beta2 thing,

Message from the browser:

XHRPOSThttps://traxlrs.kieranmathieson.com/trax/api/auth/login
[HTTP/2 419 No Reason Phrase 634ms]

    	
    message	"CSRF token mismatch."
    exception	"Symfony\\Component\\HttpKernel\\Exception\\HttpException"
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
    line	227
    trace	[ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
    0	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php", line: 199, function: "prepareException", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
    line	199
    function	"prepareException"
    class	"Illuminate\\Foundation\\Exceptions\\Handler"
    type	"->"
    1	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/app/Exceptions/Handler.php", line: 53, function: "render", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/app/Exceptions/Handler.php"
    line	53
    function	"render"
    class	"Illuminate\\Foundation\\Exceptions\\Handler"
    type	"->"
    2	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/services/trax/framework/core/src/ExceptionHandler.php", line: 26, function: "render", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/services/trax/framework/core/src/ExceptionHandler.php"
    line	26
    function	"render"
    class	"App\\Exceptions\\Handler"
    type	"->"
    3	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/services/trax/framework/xapi-store/src/Exceptions/XapiExceptionHandler.php", line: 42, function: "render", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/services/trax/framework/xapi-store/src/Exceptions/XapiExceptionHandler.php"
    line	42
    function	"render"
    class	"Trax\\Core\\ExceptionHandler"
    type	"->"
    4	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php", line: 51, function: "render", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php"
    line	51
    function	"render"
    class	"Trax\\XapiStore\\Exceptions\\XapiExceptionHandler"
    type	"->"
    5	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 172, function: "handleException", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	172
    function	"handleException"
    class	"Illuminate\\Routing\\Pipeline"
    type	"->"
    6	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php", line: 49, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php"
    line	49
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    7	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Illuminate\\View\\Middleware\\ShareErrorsFromSession"
    type	"->"
    8	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php", line: 116, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php"
    line	116
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    9	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php", line: 62, function: "handleStatefulRequest", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php"
    line	62
    function	"handleStatefulRequest"
    class	"Illuminate\\Session\\Middleware\\StartSession"
    type	"->"
    10	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Illuminate\\Session\\Middleware\\StartSession"
    type	"->"
    11	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php", line: 37, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php"
    line	37
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    12	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse"
    type	"->"
    13	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php", line: 67, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php"
    line	67
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    14	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Illuminate\\Cookie\\Middleware\\EncryptCookies"
    type	"->"
    15	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 103, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	103
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    16	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 687, function: "then", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
    line	687
    function	"then"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    17	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 662, function: "runRouteWithinStack", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
    line	662
    function	"runRouteWithinStack"
    class	"Illuminate\\Routing\\Router"
    type	"->"
    18	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 628, function: "runRoute", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
    line	628
    function	"runRoute"
    class	"Illuminate\\Routing\\Router"
    type	"->"
    19	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 617, function: "dispatchToRoute", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
    line	617
    function	"dispatchToRoute"
    class	"Illuminate\\Routing\\Router"
    type	"->"
    20	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line: 165, function: "dispatch", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
    line	165
    function	"dispatch"
    class	"Illuminate\\Routing\\Router"
    type	"->"
    21	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 128, function: "Illuminate\\Foundation\\Http\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	128
    function	"Illuminate\\Foundation\\Http\\{closure}"
    class	"Illuminate\\Foundation\\Http\\Kernel"
    type	"->"
    22	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/services/trax/framework/auth/src/Middleware/CorsMiddleware.php", line: 51, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/services/trax/framework/auth/src/Middleware/CorsMiddleware.php"
    line	51
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    23	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Trax\\Auth\\Middleware\\CorsMiddleware"
    type	"->"
    24	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php", line: 21, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php"
    line	21
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    25	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest"
    type	"->"
    26	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php", line: 21, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php"
    line	21
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    27	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest"
    type	"->"
    28	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php", line: 27, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php"
    line	27
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    29	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize"
    type	"->"
    30	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php", line: 63, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php"
    line	63
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    31	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode"
    type	"->"
    32	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/fruitcake/laravel-cors/src/HandleCors.php", line: 37, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/fruitcake/laravel-cors/src/HandleCors.php"
    line	37
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    33	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Fruitcake\\Cors\\HandleCors"
    type	"->"
    34	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/fideloper/proxy/src/TrustProxies.php", line: 57, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/fideloper/proxy/src/TrustProxies.php"
    line	57
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    35	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	167
    function	"handle"
    class	"Fideloper\\Proxy\\TrustProxies"
    type	"->"
    36	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 103, function: "Illuminate\\Pipeline\\{closure}", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
    line	103
    function	"Illuminate\\Pipeline\\{closure}"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    37	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line: 140, function: "then", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
    line	140
    function	"then"
    class	"Illuminate\\Pipeline\\Pipeline"
    type	"->"
    38	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line: 109, function: "sendRequestThroughRouter", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
    line	109
    function	"sendRequestThroughRouter"
    class	"Illuminate\\Foundation\\Http\\Kernel"
    type	"->"
    39	Object { file: "/home/cullenma/traxlrs.kieranmathieson.com/public/index.php", line: 55, function: "handle", … }
    file	"/home/cullenma/traxlrs.kieranmathieson.com/public/index.php"
    line	55
    function	"handle"
    class	"Illuminate\\Foundation\\Http\\Kernel"
    type	"->"

**Comment by sfraysse** [comment]
Hi,

Try to reload the page, the token may have expired.

If you still have the issue, could you tell me what version of Firefox you are using.
I just tested with the last version of Firefox and I don't have the issue.

Are you testing the same TRAX LRS instance with Chrome (working) and Firefox (not working)?

**Comment by sfraysse** [comment]
It could also be an issue with coockies.
The CSRF token is stored as a coockie when loading the main page.
Then it is passed to the POST request when submiting the login form.

Could you check if coockies are enabled in your Firefox settings?
