### ISSUE TITLE
Missing files or folder

### ISSUE THREAD

**Issue by taddeus73** [trax-project/trax2-starter-lrs#20]
missing file/fodler in the folder services: tim and framework ?

**Comment by taddeus73** [comment]
when I run the command:
npm run dev

I get the following messages...

> dev
> npm run development


> development
> mix


✖ Mix
  Compiled with some errors in 4.44s

ERROR in ./services/trax/lrs/resources/js/app/pages/clients/ClientsCrud.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??clonedRuleSet-5[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./services/trax/lrs/resources/js/app/pages/clients/ClientsCrud.vue?vue&type=script&lang=js&) 69:0-58
Module not found: Error: Can't resolve '@trax/classes/CrudController' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app/pages/clients'

ERROR in ./services/trax/lrs/resources/js/app/pages/settings/ClearAll.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??clonedRuleSet-5[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./services/trax/lrs/resources/js/app/pages/settings/ClearAll.vue?vue&type=script&lang=js&) 28:0-62
Module not found: Error: Can't resolve '@trax/classes/ModalsController' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app/pages/settings'

ERROR in ./services/trax/lrs/resources/js/app/pages/statements/StatementsResult.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??clonedRuleSet-5[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./services/trax/lrs/resources/js/app/pages/statements/StatementsResult.vue?vue&type=script&lang=js&) 106:0-62
Module not found: Error: Can't resolve '@trax/classes/ModalsController' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app/pages/statements'

ERROR in ./services/trax/lrs/resources/js/app/components/SidebarPlugin/index.js 2:0-82
Module not found: Error: Can't resolve '@tim/black/src/components/SidebarPlugin/SidebarLink.vue' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app/components/SidebarPlugin'

ERROR in ./services/trax/lrs/resources/js/app/components/TopbarPlugin/index.js 1:0-52
Module not found: Error: Can't resolve '@trax/classes/ToggleState' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app/components/TopbarPlugin'

ERROR in ./services/trax/lrs/resources/js/app/i18n.js 1:0-52
Module not found: Error: Can't resolve '@trax/classes/I18nFactory' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app'

ERROR in ./services/trax/lrs/resources/js/app/i18n.js 5:17-84
Module not found: Error: Can't resolve '@trax/locales' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app'

ERROR in ./services/trax/lrs/resources/js/app/main.js 5:8-48
Module not found: Error: Can't resolve '@trax/plugins/Auth' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app'

ERROR in ./services/trax/lrs/resources/js/app/main.js 11:8-54
Module not found: Error: Can't resolve '@trax/plugins/XapiClient' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app'

ERROR in ./services/trax/lrs/resources/js/app/routing.js 1:0-56
Module not found: Error: Can't resolve '@trax/classes/RouterFactory' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js/app'

ERROR in ./services/trax/lrs/resources/js/lib.js 5:12-78
Module not found: Error: Can't resolve '@tim/black/src/components/NotificationPlugin' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/js/lib.js 7:35-98
Module not found: Error: Can't resolve '@tim/black/src/directives/click-ouside.js' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/js/lib.js 9:32-93
Module not found: Error: Can't resolve '@tim/black/src/components/BaseAlert.vue' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/js/lib.js 10:33-95
Module not found: Error: Can't resolve '@tim/black/src/components/BaseButton.vue' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/js/lib.js 11:26-88
Module not found: Error: Can't resolve '@tim/black/src/components/Cards/Card.vue' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/js/lib.js 12:35-99
Module not found: Error: Can't resolve '@tim/black/src/components/BaseDropdown.vue' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/js/lib.js 13:35-99
Module not found: Error: Can't resolve '@tim/black/src/components/BaseCheckbox.vue' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/js/lib.js 14:32-93
Module not found: Error: Can't resolve '@tim/black/src/components/BaseRadio.vue' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/js/lib.js 15:32-93
Module not found: Error: Can't resolve '@tim/black/src/components/BaseTable.vue' in '/Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/js'

ERROR in ./services/trax/lrs/resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import '@tim/black/src/assets/sass/black-dashboard';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /Applications/MAMP/htdocs/trax2/services/trax/lrs/resources/sass/app.scss 1:9  root stylesheet
    at processResult (/Applications/MAMP/htdocs/trax2/node_modules/webpack/lib/NormalModule.js:753:19)
    at /Applications/MAMP/htdocs/trax2/node_modules/webpack/lib/NormalModule.js:855:5
    at /Applications/MAMP/htdocs/trax2/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Applications/MAMP/htdocs/trax2/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Applications/MAMP/htdocs/trax2/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Applications/MAMP/htdocs/trax2/node_modules/sass-loader/dist/index.js:73:7
    at Function.call$2 (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:99051:16)
    at render_closure1.call$2 (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:84557:12)
    at _RootZone.runBinary$3$3 (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:29579:18)
    at _FutureListener.handleError$1 (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:28099:21)
    at _Future__propagateToListeners_handleError.call$0 (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:28406:49)
    at Object._Future__propagateToListeners (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:3909:77)
    at _Future._completeError$2 (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:28252:9)
    at _AsyncAwaitCompleter.completeError$2 (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:27900:12)
    at Object._asyncRethrow (/Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:3712:17)
    at /Applications/MAMP/htdocs/trax2/node_modules/sass/sass.dart.js:19793:20

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 21 errors

**Comment by sfraysse** [comment]
If you want to recompile the UI, you will need:
- A copy of Vue Black Dashboard template from Creative Tim: https://www.creative-tim.com/product/vue-black-dashboard
- A copy of TRAX Framework which is currently in your vendor folder, or you can just adapt the `@trax` alias in the `webpack.mix.js` file

**Comment by taddeus73** [comment]
Ok ..but ... how can I copy and compile Vue Black Dashboard in the poroject?

**Comment by sfraysse** [comment]
You get the files from Creative Tim (it's a free download) and you put them in a folder named `services/tim/black`. Then you can run `npm run dev`. Of course, you don't have to do that to use TRAX LRS. It is just in case you want to modify the UI and recompile it.

**Comment by taddeus73** [comment]
great! It works!
thanks Sébastien
