### ISSUE TITLE
Moodle Integration

### ISSUE THREAD

**Issue by taddeus73** [trax-project/trax2-starter-lrs#21]
hi I configured my TRAX LRS 2.01 server and I would like to use it by Moodle platform version 3.9.
I need help to configure external content plugin in particular I need I List of completion xAPI verbs ... can anyone help me please 😀?

**Comment by sfraysse** [comment]
Hi @taddeus73,

You can use **TRAX Logs plugin for Moodle** to integrate your Moodle 3.9 with any compliant LRS (not only TRAX LRS): https://github.com/trax-project/moodle-trax-logs

I close this issue because this is not a TRAX LRS related issue, but a Moodle related issue.
