### ISSUE TITLE
Setting up Elasticsearch Connector

### ISSUE THREAD

**Issue by DonavanMartin** [trax-project/trax2-starter-lrs#22]
Hi, 
According to the Elasticsearch Connector [documentation](https://extended.traxlrs.com/docs/2.0/elasticsearch)... 
I wasn't able to run any of those commands:
```
php artisan statements:elastic-push
php artisan agents:elastic-push
php artisan activities:elastic-push
php artisan agent-profiles:elastic-push
php artisan activity-profiles:elastic-push
```

Do I need the extended version to run those commands ?

**Comment by sfraysse** [comment]
Hi,
Yes, all the features described in this documentation are related to the Extended Edition.
Best regards.
