### ISSUE TITLE
Internal servor error

### ISSUE THREAD

**Issue by antikkorps** [trax-project/trax2-starter-lrs#23]
Bonjour,

J'ai suivi la procédure d'installation jusqu'au bout. 
Tout semble fonctionner correctement mais j'obtiens une Internal Server Error.
J'ai bien accès aux lignes de commandes, les dossiers public et bootstrap sont correctement configuré, l' APP Key est ok, ma migration a bien été réalisée sans erreur, j'ai pu créer mon utilisateur admin mais je n'ai pas accès à l'interface. 
Grosso modo c'est après la migration que l'erreur intervient et je n'arrive pas à identifier le soucis.
Le serveur est en Debian, MySql 5.7.

Merci d'avance si vous avez une idée.

**Comment by sfraysse** [comment]
Bonjour,
Difficile de solutionner le problème comme ça. Mais voici quelques pistes :
- Version PHP et config PHP à la fois CLI et Web (2 fichiers INI)
- Droits en écriture sur les dossiers `storage` et `bootstrap`
- Pointage du serveur sur votre dossier `public`

**Comment by antikkorps** [comment]
Merci pour les pistes.

Je ne pense pas que ça vienne des droits en écriture, j'y ai fait attention parce que c'est la première chose qui m'est venue à l'esprit.
Le serveur pointe bien vers le dossier public.
Est-ce que vous pouvez me préciser le premier point concernant PHP?

Le host (Ionos) me parle plutôt du fichier web.config (utilisation sur serveur windows à priori) mais je ne pense pas que ça soit ça. 

Merci encore.

**Comment by sfraysse** [comment]
Concernant PHP, les pré-requis sont dans la procédure d'installation.

Je voulais attirer votre attention sur le fait que PHP s'utilise de 2 manière : CLI (lignes de commandes) et serveur Web.
Ces 2 utilisations de PHP font généralement l'objet de 2 configurations séparées sur votre serveur (PHP.ini).
Toutes deux doivent respecter les prérequis PHP.

Je peux difficilement vous aider plus sans connaître votre serveur.
Je ne peux que vous conseiller de reprendre la procédure et vérifiez scrupuleusement tous les points.
