### ISSUE TITLE
PHP Fatal error:  Trait 'Trax\DataStore\Utils\Transaction' not found in /opt/lampp/htdocs/trax-lrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php 

### ISSUE THREAD

**Issue by vishnuchoudhary2822** [trax-project/trax2-starter-lrs#26]
[Wed Apr  5 13:51:12 2023] PHP Fatal error:  Trait 'Trax\DataStore\Utils\Transaction' not found in /opt/lampp/htdocs/trax-lrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php on line 15
[Wed Apr  5 13:51:16 2023] PHP Fatal error:  Trait 'Trax\DataStore\Utils\Transaction' not found in /opt/lampp/htdocs/trax-lrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php on line 15
[Wed Apr  5 13:51:17 2023] PHP Fatal error:  Trait 'Trax\DataStore\Utils\Transaction' not found in /opt/lampp/htdocs/trax-lrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php on line 15
[Wed Apr  5 13:51:17 2023] PHP Fatal error:  Trait 'Trax\DataStore\Utils\Transaction' not found in /opt/lampp/htdocs/trax-lrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php on line 15
[Wed Apr  5 13:51:17 2023] PHP Fatal error:  Trait 'Trax\DataStore\Utils\Transaction' not found in /opt/lampp/htdocs/trax-lrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php on line 15
[Wed Apr  5 13:51:17 2023] PHP Fatal error:  Trait 'Trax\DataStore\Utils\Transaction' not found in /opt/lampp/htdocs/trax-lrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php on line 15
[Wed Apr  5 13:51:18 2023] PHP Fatal error:  Trait 'Trax\DataStore\Utils\Transaction' not found in /opt/lampp/htdocs/trax-lrs/vendor/trax/framework/data-store/src/Http/Controllers/DataWsController.php on line 15

**Comment by sfraysse** [comment]
You are trying to deploy TRAX LRS v1.0.
Please, move to TRAX LRS v2.0.

**Comment by vishnuchoudhary2822** [comment]
Can you send me TRAX LRS v2.0 URL Please
