### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by vishnuchoudhary2822** [trax-project/trax2-starter-lrs#27]
http://127.0.0.1:8000/lrs/clients

I created the client and Endpoint URL http://127.0.0.1:8000/trax/api/0dd0ef5c-0952-4323-bf45-fff655811a65/xapi/std but still not working 404 not found showing Please help

**Comment by sfraysse** [comment]
You need to add the name of the API at the end of the endpoint.
Please, review the docs and review the xAPI spec before asking questions here.
Best regards
