### ISSUE TITLE
Build issues npm

### ISSUE THREAD

**Issue by jefsev** [trax-project/trax2-starter-lrs#28]
Hi,

The frontend of the application is not working for me. Whenever i build i get a lot of building errors:

<img width="1420" alt="Screenshot 2023-09-06 at 10 00 43" src="https://github.com/trax-project/trax2-starter-lrs/assets/28394100/756ce9a3-37de-49fe-a7fc-466156755f28">

To me it looks like a lot is missing.

Let me know what to do?

**Comment by jefsev** [comment]
Also in app.scss:

@import '@tim/black/src/assets/sass/black-dashboard';

<img width="1306" alt="Screenshot 2023-09-06 at 10 12 53" src="https://github.com/trax-project/trax2-starter-lrs/assets/28394100/22c86cbc-d3d3-4e90-9d5c-52699d1981b6">

But @tim seems to be nowhere, so that also results in an error on build, if i comment this out i get all the above errors in the screenshot.

**Comment by sfraysse** [comment]
Hi jefsev,

> the frontend of the application is not working for me

I am not sure that rebuilding the front-end will solve your issue. What do you mean by "is not working"?

If you still want to rebuild the front-end, you need to install a template in the `services/tim/black` folder: Vue-Black Dashboard (1.1.0 - 2019-02-12) from Creative Tim.

However, be aware that this template is not maintained anymore so it will be removed with TRAX LRS 3.0.

**Comment by jefsev** [comment]
When i cloned the repo and followed the steps but nothing showed in the browser. So i thought i should run npm install and build. But no succes.

**Comment by sfraysse** [comment]
First of all, restart from a fresh install.
Nothing showed in the browser, ok, but what is in the browser console?
Do you get errors, what happens in the HTTP requests?
