### ISSUE TITLE
Augmenter nombre de statements autorisés

### ISSUE THREAD

**Issue by sloopint** [trax-project/trax2-starter-lrs#29]
Bonjour Sébastien,

Tout d’abord, un grand merci pour ce fantastique outil.
Je suis enseignant et j’utilise Trax à des fins pédagogiques (même si j’envisage une application commerciale à plus grande échelle). Concrètement, j’ai une application en ligne qui intègre h5p sur mon site web. Les élèves doivent répondre à des questions. L’api de h5p renvoie correctement les statements vers Trax.
Ensuite, je récupère les statements de Trax pour en tirer des graphiques et une table.
Jusqu’à présent, j’utilisais Trax starter 1.0.0. Le problème, c’est qu’au-delà de 1000 statements, ça ne fonctionnait plus. Dans le fichier config/trax-xapi-server.php, en augmentant le nombre de statements autorisés grâce à XAPI_SERVER_LIMIT, je pouvais passer outre.
Je viens de passer à Trax starter 2.0.0 (Je ne peux pas pousser jusqu’à 2.0.4 car la version de MySql de mon hébergement ne le permet pas.) Cette fois, je remarque que cette version est limitée par défaut à 100 statements. Je ne trouve rien dans le code permettant d’aller au-delà. Comme indiqué dans la documentation, j’ai mis dans le fichier .env XAPI_STATEMENTS_LIMIT avec un nombre de statements supérieur à 100. J’ai fait de même avec XAPI_SERVER_LIMIT. J’ai aussi mis production à la place de local. Mais ces trois solutions n’ont pas marché.
Y a-t-il alors un moyen de « débrider » Trax starter pour collecter davantage que les 100 derniers statements ?
Merci de m’apporter vos lumières.

Dominique

**Comment by sfraysse** [comment]
Bonjour Dominique,

En effet, dans TRAX LRS 2.0 Starter Edition, il n'y a pas de variable de conf pour régler le nombre de statements retournés qui est fixé à 100. Dans TRAX LRS 2.0 Extended Edition, il y a un paramètre `XAPI_STATEMENTS_LIMIT` qui sert à ça.

Je pourrais le rajouter à la Starter mais il n'y a pas de release prévue dans l'immédiat, les efforts étant maintenant portés sur le version 3.0. Mais je garde l'idée sous le coude.

En revanche, je m'interroge sur l'intérêt d'augmenter ce paramètre. En effet, il ne s'agit que d'un réglage de pagination, c'est à dire le nombre de statements renvoyés à chaque requête GET, sachant que l'on dispose du lien pour aller chercher les N suivants, et ainsi de suite. La réponse à un GET renvoie en effet une propriété `more` qui permet d'aller chercher les N statements suivants.

Si vous avez à faire un GET en grand nombre, il est important d'utiliser ce système de pagination qui est complètement standardisé. Car plus vous réclammez de statements à chaque requête, plus vous chargez la RAM du serveur et la taille de la réponse. Il y a donc de toute façon une limite physique.
