### ISSUE TITLE
Where is the xAPI endpoint?

### ISSUE THREAD

**Issue by Darksonn** [trax-project/trax2-starter-lrs#3]
On the non-beta version, the github readme lists the following endpoint for the xAPI:
```
http://trax.test/trax/ws/xapi
```
I have installed the beta version and tried various variations of the above endpoint, but none of them worked. What is the correct path? The path I get when logging in is `http://192.168.168.119/lrs/home`

**Comment by sfraysse** [comment]
When you refer to the "non-beta" version, you refer to **TRAX LRS version 1**.
We are here on **TRAX LRS version 2 (beta)**.

To find the endpoint on TRAX LRS 2, create a client, then click on the (i) button which gives you a specific endpoint for this access.

**Comment by Darksonn** [comment]
Yes, exactly, I was trying to find the equivalent of the url from TRAX LRS version 1 in version 2 (beta). The (i) button was indeed the missing piece.
