### ISSUE TITLE
Faire des requêtes sur un grand volume de données

### ISSUE THREAD

**Issue by sloopint** [trax-project/trax2-starter-lrs#30]
Bonjour Sébastien,

Je reviens vers vous pour vous remercier de votre réponse à mon précédent post. Cela m’a permis d’augmenter le nombre de statements collectés sur la version Starter 2.0.0.

Ce qui m’inquiète, c’est quand vous dites qu’il y a une « limite physique ». Quel serait le meilleur moyen de la reculer ? La version Extended permet-elle de gérer cela ? Avec quel type de bdd ?

Pour résumer, je cherche à faire un suivi pédagogique d’élèves sur une année scolaire. (Au mois d’août, le compteur reviendrait à zéro.) Par élève, les statements au fil des mois seraient de plus en plus nombreux et pourraient atteindre plusieurs milliers. J’aimerais aussi collecter des statements par classe d’élèves (d’où un nombre de statements encore bien plus élevé). Et j’espère intéresser un nombre assez conséquent de classes…

Le suivi des élèves se ferait via des graphiques synthétisant des informations s’échelonnant sur plusieurs mois. (Résultats individuels à des activités h5p destinés à chaque élève et résultats collectifs par classe destinés au professeur.)

Tout cela fonctionne très bien avec Trax à petite échelle. Mais qu’en serait-il si le volume à traiter devient plus important ?

Autre souci : mon hébergeur utilise la version 10.5.22 de MariaDB. Est-ce que cela pose problème pour passer de Trax 2.0.0 à Trax 2.1 ? 

Encore merci pour le temps que vous passerez à m'aiguiller.

Dominique

**Comment by sfraysse** [comment]
Bonjour Dominique,

La version 2 Extended a plusieurs options permettant d'améliorer les performances en fonction des Use Cases.
La version 3 va aussi apporter des améliorations de performances significatives.

Par ailleurs, toujours préférer PostgreSQL à MySQL et MariaDB pour les performances. D'ailleurs MariaDB va être abandonné en version 3 car cette BD a trop de limites sur le support du format JSON. MongoDB et Elasticsearch seront aussi peut-être à considérer en fonction de vos besoins avec la version 3.

Enfin, et c'est à mon sens là le plus important, il vous faut probablement reconsidérer votre approche des flux de données pour parvenir à votre résultat. En effet, faire des GET dans un LRS avec une très large pagination dans le but de ne pas utiliser cette pagination pause question.

J'imagine que vous souhaiter procéder ainsi pour analyser directement vos données à chaque requête, mais ce n'est en effet pas une approche scalable. Le problème n'est pas le LRS ni la base de données, c'est l'approche. Les traces xAPI ne sont qu'un système de logs (d'événements). Faire des analyses nécessite une phase de transformation et agrégation intermédiaire avant affichage. Je vous recommande de jeter un œil aux approches CQRS qui illustrent bien ces problématiques.

J'espère vous avoir un peu aidé.

**Comment by sloopint** [comment]
Bonjour Sébastien,

Merci pour vos précieux conseils. Je vais étudier cette épineuse question...
Pour l'heure, j'ai un problème plus basique. J'ouvre un nouveau topic.
