### ISSUE TITLE
problème de connexion en admin

### ISSUE THREAD

**Issue by haithamRD** [trax-project/trax2-starter-lrs#31]
j'arrive pas à me connecter à l'interface admin je reçois une erreur Unwaited error (status 500). sur mon inspecteur Auth.js:144 
[ 
 GET http://localhost:1432/trax/api/front/users/me?accessors[]=permissions&relat…ty&relations[]=role&include[]=owners&include[]=csrf-token&include[]=config 500 (Internal Server Error)](http://localhost:1432/trax/api/front/users/me?accessors[]=permissions&relations[]=owner&relations[]=entity&relations[]=role&include[]=owners&include[]=csrf-token&include[]=config)

message | 'Attempt to read property "id" on null'
exception | "ErrorException"
 in /var/www/app/vendor/trax2/framework/auth/src/Stores/Users/UserController.php"

si vous pouvez m'aider à régler ce problème

**Comment by haithamRD** [comment]
{message: "Attempt to read property "id" on null", exception: "ErrorException",…}
exception
: 
"ErrorException"
file
: 
"/var/www/app/vendor/trax2/framework/auth/src/Stores/Users/UserController.php"
line
: 
129
message
: 
"Attempt to read property \"id\" on null"
trace
: 
[{file: "/var/www/app/vendor/trax2/framework/auth/src/Stores/Users/UserController.php", line: 129,…},…]

**Comment by sfraysse** [comment]
Bonjour,
Pouvez-vous me confirmer la version de TRAX LRS que vous utilisez : 2.1 Starter ?

**Comment by sfraysse** [comment]
Pouvez-vous m'en dire plus sur le contexte de cette erreur ?
Est-ce une installation fraiche qui n'a jamais fonctionné ?
Est-ce que ça fait suite à une mise à jour ?
Je suis preneur de toute information qui m'aiderait à mieux comprendre le problème.

**Comment by haithamRD** [comment]
bonjour @sfraysse ,
aprés une fraiche installation sans aucune erreur. j ai crée un compte admin lorsque je me connecte il me donne erreur unwaited error 500 après avoir analyser le code sous l inspecteur la fonction showMe in UserController la valeur $authenticator-> user()-id; is null  comme il est définit en haut

**Comment by haithamRD** [comment]
> Bonjour, Pouvez-vous me confirmer la version de TRAX LRS que vous utilisez : 2.1 Starter ?

j ai cloner ce starter kit c est bien 2.1

**Comment by sfraysse** [comment]
OK, problème assez curieux et jamais rencontré.
Quel navigateur utilisez-vous ? Merci d'essayer sous Chrome si ce n'est pas le cas.
Pas de restriction sur les coockies sur votre navigateur ?
Peut-être un problème de cache : essayez de vider toutes les données relatives à ce site sur votre navigateur.
Rechargez bien la page avant de réessayer.

**Comment by haithamRD** [comment]
j'utilise Chrome , et sans aucune restriction sur les cookies , je 'ai même utilisé une fenêtre invité pour éviter les cookies et je trouve toujours un soucis dans cette endpoint **http://localhost:1432/trax/api/front/users/me?accessors[]=permissions&relations[]=owner&relations[]=entity&relations[]=role&include[]=owners&include[]=csrf-token&include[]=config** 
![endpoint-error](https://github.com/trax-project/trax2-starter-lrs/assets/34986651/b6cab06e-b0b9-4e68-9afe-8c27a97bcad4)
![error](https://github.com/trax-project/trax2-starter-lrs/assets/34986651/5f12a009-5689-4c87-bb97-ca6154710b2b)

**Comment by sfraysse** [comment]
Je viens de re-tester l'installation de la 2.1 sans souci.
Par contre je vois 2 requêtes dans votre console : la première en erreur 401 et la seconde en 500.
Est-ce que ça signifie que votre 1ère tentative de login se solde par un 401, et la seconde tentative par un 500 ?

**Comment by sfraysse** [comment]
Ou bien ces 2 requêtes s'enchaînent-elles automatiquement ?

**Comment by sfraysse** [comment]
Autre question : ces 2 requêtes portent-elles exactement sur le même endpoint avec les mêmes params et contenus ? (merci d'examiner les 2 requêtes dans l'onglet network).

Autre question : j'essaie de comprendre pourquoi vous avez une erreur 401 en premier. Avez-vous créé un admin depuis la console ? Si oui, avez-vous inclus des caractères spéciaux lors de la création de l'admin (dans ce cas recommencer avec des caractères standards) ?
