### ISSUE TITLE
404 when trying to access the xAPI endpoints

### ISSUE THREAD

**Issue by mstimvol** [trax-project/trax2-starter-lrs#4]
I've installed the LRS and created a client successfully. But when I copy the service endpoint url of the client and configure my LMS using this URL, I receive no statements. So I tried to open the URL directly in my browser and also sent a POST request to the endpoint using Postman. But I always receive a 404 message. Any idea what causes the error?

**Comment by sfraysse** [comment]
Take the endpoint, add `/about` at the end, and open it in a browser.
What do you see?

**Comment by mstimvol** [comment]
I'm getting an error "Route [login] not defined":

![Screenshot_2021-03-04 🧨 Route  login  not defined ](https://user-images.githubusercontent.com/67418257/109957992-ff72ca00-7ce5-11eb-977c-cbc4a5e3ce1b.png)

**Comment by sfraysse** [comment]
Did you create a virtual host that points to the public folder?
https://github.com/trax-project/trax2-starter-lrs#web-server

**Comment by mstimvol** [comment]
I was finally able to solve the issue. The virtual host was correct but in my LMS I configured the URL without the trailing / (because the example in the moodle-trax-logs plugin say without trailing slash). I'm finally getting the statements from my LMS in TRAX. But the /about page still doesn't work. So the error above still exists in my case.

**Comment by sfraysse** [comment]
Right, the way you configure the endpoint depends of the LMS.
So you configured your LMS with `endpoint/`.

If the LMS can send statements, it means the statements API works (URL: `endpoint/statements`).
So the about API should also work (URL: `endpoint/about`).
Are you sure the endpoint is exactly the same?

Anyway, this was just for testing. If your LMS works, it's OK. I close this issue.

**Comment by HichemUchiwa** [comment]
Hello
I have almost the same issue. I followed all steps of the installation and URL: endpoint/about works. However the URL: endpoint/statements doesn't work and like @mstimvol when I copy the service endpoint url of the client and configure my LMS using this url, I receive no statements.
Thank you for considering my request :)

**Comment by rimkov** [comment]
I installed the trax-starter but the url endpoint does not work, I have a 404 error. url found on client page : 

`/trax/api/e21d445f-1de7-47ec-a6e1-c39e9dcac17d/xapi/std `

mdl_logstore_trax_logs table is empty

the root directory is correctly set to public

thank you for your help

**Comment by sfraysse** [comment]
`/trax/api/e21d445f-1de7-47ec-a6e1-c39e9dcac17d/xapi/std` is just the base of the endpoint. Please check the xAPI spec for the full URLs.

Or check `http://your.lrs.domain/trax/api/e21d445f-1de7-47ec-a6e1-c39e9dcac17d/xapi/std/about` to see if you can access to the about endpoint.

`mdl_logstore_trax_logs` is a Moodle table and has nothing to see with TRAX LRS.
