### ISSUE TITLE
Login fails for every admin user

### ISSUE THREAD

**Issue by jmayermsi** [trax-project/trax2-starter-lrs#5]
Hello, Generated new users using the default settings for admin using Beta 4. Every time I try to login I get a login failure: Unknown user or wrong password.   I tried creating a new user using the artisan create method. The user is created but again the login fails each time. Tested with both chrome and edge browsers. Looked in the database to see if the user is being created and it is. Not sure what is happening.  When the password is created can I decrypt myself to see what is happening or is there some flag in the database not being sent.

**Comment by sfraysse** [comment]
Hi @jmayermsi,
No, you can't decrypt the password and the reason of this error is not necesserally related to your password.
To be sure, create an admin with the password `aaaaaaaa` and check if you works.
If it still does not work, open the Chrome console, Network tab, see what is the response to the login request and tell me.

**Comment by Chrystele3700** [comment]
Bonjour M. Fraysse,

J'ai exactement le même problème.
J'ai modifié le mot de passe comme demandé. Cela ne fonctionne pas.
Erreur 404.
Dans le fichier de log: File does not exist /var/www/html/traxlrs/vendor/trax/api/auth/login

En effet, le répertoire /var/www/html/traxlrs/vendor/trax n'existe pas.

J'ai pourtant scrupuleusement suivi  l'installation pas à pas (et refaite 2 fois).
En vous remerciant pour votre aide; nous reprenons enfin! les essais.

Cordialement,

Chrystèle (nous avions suivi votre formation en décembre dernier)
