### ISSUE TITLE
Configuration Flags

### ISSUE THREAD

**Issue by danielband** [trax-project/trax2-starter-lrs#6]
Hey, 

are XAPI_STORE_PROFILE, XAPI_STATEMENTS_AUTHORITY_NAME and XAPI_STATEMENTS_AUTHORITY_HOMEPAGE flags extended edition features? It is not flagged as such in the documentation, but those are not working with the starter lrs. I cant find any reference of those flags in the code either.

Thanks

**Comment by sfraysse** [comment]
Hi,
All the documentation at http://extended.traxlrs.com/docs/2.0 is related to the Extended Edition.
