### ISSUE TITLE
ValidationException errors not propagated

### ISSUE THREAD

**Issue by jeremyVignelles** [trax-project/trax2-starter-lrs#7]
I'm trying to integrate the LRS with an activity generated by iSpring QuizMaker, and all I got from the network tab from my browser was this:

> One or more request inputs are not valid: 

Which is not very helpful without the actual error list

To get something helpful, I had to replace this line:

https://github.com/trax-project/trax2-framework/blob/365cca174f0cd8541df81f79e6fbc2245c7663cc/xapi-store/src/Abstracts/XapiController.php#L143

to : 

```php

            throw new XapiBadRequestException('One or more request inputs are not valid: '. "\n" . json_encode($e->errors()), $e->errors());
```

**Comment by sfraysse** [comment]
Hi Jeremy,
Thanks for the improvement. It's on the dev branch and it will be in the next release.
