### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jeremyVignelles** [trax-project/trax2-starter-lrs#8]
I've seen that docker support is on [the roadmap](http://extended.traxlrs.com/docs/2.0/roadmap).

What exactly is meant by that? docker images for production? docker development container ?

I have set up a docker environment locally, and I'd be happy to make a PR to add this support.

PS: I've sent you an e-mail through the website a few days ago, but I didn't get any confirmation. Did you get it?

**Comment by sfraysse** [comment]
Hi Jeremy,

Docker support means docker images for production.
The Extended Edition will have some optional behaviors which may require things like Redis cache, queues management and so on. However, the Extended Edition which is not currently stable so it's too soon to propose such images. And the Starter Edition may be affected by the next updates too.

Thank you for your PR. I will merge it or adapt it at the end of the dev cycle.
