### ISSUE TITLE
website: sponsor section gets blocked by uBlock origin

### ISSUE THREAD

**Issue by jeremyVignelles** [trax-project/trax2-starter-lrs#9]
Just to inform you that uBlock origin completely blocks the "sponsor" section on the website:

![image](https://user-images.githubusercontent.com/3399355/128509663-805ff690-f148-4b90-b600-e430d3b2e546.png)

It also seem to remove the accordion items in the FAQ after you've expanded and collapsed them :
![image](https://user-images.githubusercontent.com/3399355/128509799-b6d183ae-9922-4805-9a63-aa0c06798638.png)

**Comment by sfraysse** [comment]
Thanks for the feedback Jeremy!

However, I don't know the criteria UBlock uses to decide to hide page elements:
- Presence of a contact form?
- Presence of some key words (sponsor, pricing, etc.)?
- Presence of logos?
- No HTTPS?

I you have any idea how to bypass UBlock rules, I take it...

**Comment by jeremyVignelles** [comment]
> - Presence of a contact form?

The contact form is not impacted

> - Presence of some key words (sponsor, pricing, etc.)?

Probably this one and/or specific ids/classes. If I remember correctly, they block based on CSS-like rules.


> - Presence of logos?

I don't see how they could detect that...

> - No HTTPS?

Probably not for ublock, but that's a good habit anyway

**Comment by sfraysse** [comment]
Problem solved with the last update of the website.
